# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2693340d868366baa69b993cdfcc6c36db3b429ab004a2c7f33e99b849fb086d5ee04e690d50195482ed0f78d4a5b5ddac3cc3a694b214e2f67bd4f1386f9410

test:
  secret_key_base: 2ec7aa31323d8d2bfb182e1011c6844241ef31165f4e61f4ca4d897d857fb0e204b2cea5433218ffc6977a6e1740a050e218e3c633b7eb740aff13efb07a4cb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
